spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkukielka_dev
    username: kkukielka_dev_user
    password: kkukielka
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true