spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/kkukielka_prod
    username: kkukielka_prod_user
    password: kkukielka
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true